### ISSUE TITLE
请问在CH582中TMOS调用的SysTick_Config和您PortoThread的SysTick_Config传参不同，难道不会冲突吗？

### ISSUE THREAD

**Issue by WangShuoran** [mx1117/ProtoThread-Templates#1]
在实际调用的时候，PortoThread中的systick后调用，那么会对TMOS产生影响吗？

我有简单了解TMOS的唤醒时间为625US的时间，那么如果Systick改短的话，会使TMOS的调度更频繁吧？

![image](https://github.com/smartmx/ProtoThread-Templates/assets/43474491/36374a4e-3a3a-4b3c-93bd-8ad1fe33d135)

**Comment by smartmx** [comment]
冲突，蓝牙初始化后，pt重新初始化了。TMOS调度不是用的systick，是rtc，systick是用来做蓝牙库中的随机数种子。

**Comment by WangShuoran** [comment]
谢谢，让我明白TMOS即使使用冲突的systick也没有太大问题。那么看来RTC的使用需要注意，那么您这边RTC初始化是在TMOS初始化前还是后呢？
并且RTC中有两个中断，我们是不是在使用BLE的时候，只能用其中触发模式，而不能使用定时模式？
![image](https://github.com/smartmx/ProtoThread-Templates/assets/43474491/cb06da7b-c1f6-4a09-a7df-4c7f9ea1ad9d)

**Comment by smartmx** [comment]
在使用BLE的时候，RTC不能自行另外使用，蓝牙时间全部依靠RTC，修改RTC会导致蓝牙无法使用。
