### ISSUE TITLE
在CH583项目中使用您的例程并更新工具包，发现在开启HAL_SLEEP宏定义功能时无法正常执行项目

### ISSUE THREAD

**Issue by WangShuoran** [mx1117/ProtoThread-Templates#2]
您好，因为CH583协议标准库升级为V1.2版本，并且您移植的Contiki-NG也升级到V4.9版本，我尝试按照您的思路移植了一次。确实在正常功能情况下没有什么问题。
但是当我打开HAL_SLEEP功能时会有停止执行的效果(我现在暂时还不知道问题出在哪里)，一般可能有两个：
1. 睡死了
2. 唤醒中断未定义

因为RTC唤醒，上次向您提问的问题中发现蓝牙已经管理的RTC功能，所以我认为第二个可能情况不大。
所以就找HAL_SLEEP影响的区域，最终发现了这个不同：
![image](https://github.com/smartmx/ProtoThread-Templates/assets/43474491/43858492-6995-45e3-90a1-dcdfb1ca6ef3)
所以，我不知道如何排查可能的问题，希望您这边百忙中给些升级思路。

PS:如果可以顺便解释下HAL_SLEEP的效果，谢谢啦！

**Comment by smartmx** [comment]
跟这些都没关系，contiki跟tmos无法同时运作管理睡眠。尽量不要使用。如果是contiki不继续运行了，应该是sysytick掉电导致的，睡眠唤醒后重新初始化systick即可。

**Comment by WangShuoran** [comment]
那我理解您的意思就是我说的睡死了这个原因，但是如果您说的这个重新初始化systick的话，我该如何在代码层面解决这个问题。
您提到尽量不要使用，是指不要在HAL_SLEEP使能的情况下使用这个模板吗？
因为我看您就可以做到这两者兼容，并且HAL_SLEEP我也尝试在您的项目中置位为1使能了，您是怎么做到的？

**Comment by WangShuoran** [comment]
按照您的思路，我也查验了下您设计的例程，并查找了一个比较完善的资料：
https://www.cnblogs.com/gscw/p/16349577.html
其中讲到我们的蓝牙睡眠模式默认为sleep模式，可根据实际需求作相应的修改。那么我也是默认的sleep模式，所以看看sleep的唤醒事件只有IO，RTC，BAT电压。
![image](https://github.com/smartmx/ProtoThread-Templates/assets/43474491/9e9243b8-876d-4ba9-9d3e-dc1b8778b4f8)

根据我理解你说的sysytick掉电导致这个情况，那么上电后，我只有在上述中断中恢复systick功能。
那么是不是需要我们在中断执行SysTick_Config函数，但并没有看到您的模板执行这个功能。

**Comment by smartmx** [comment]
提供的模板不支持睡眠，最好不要启用睡眠。睡眠是和tmos一体的，受tmos调度管理，tmos无法管理contiki。所以两个系统时最好不要睡眠。tmosd的睡眠在HAL/SLEEP.c中，在睡醒后自己调用SysTick_Config即可。

**Comment by WangShuoran** [comment]
是，我又仔细看了一次，发现并没有执行process的任务，谢谢您耐心解答。

**Comment by WangShuoran** [comment]
https://www.wch.cn/bbs/thread-117243-1.html
已经有官方解答：睡眠唤醒后，systick停止，需要重新初始化。

使用蓝牙的时候，进入睡眠只需要开启HAL_SLEEP，唤醒的方式为GPIO唤醒和tmos任务唤醒。唤醒后执行完成任务会自动进入睡眠的，无需再自己调用睡眠。因此只需要管理好自己的唤醒以及执行的任务。

**Comment by WangShuoran** [comment]
刚刚，我重新测试了一边移植情况，我的会有死机，但您工程打开HAL_SLEEP只是systick不执行。
得到官方的答案是需要把新版BLE中多的`cfg.SelRTCClock |= 0x80;`屏蔽。
<img width="901" alt="fccfad50fee7e5501cdbaa3dc5d761b" src="https://github.com/smartmx/ProtoThread-Templates/assets/43474491/cba604ba-bb13-43db-ba9b-67eb9bad1c77">
也就是下面这个有问题：
![06c442b231887f160b2673e3518c6fa](https://github.com/smartmx/ProtoThread-Templates/assets/43474491/a9453e99-5c1c-4185-866a-667b7511d1a2)
